name: CD-Workflow

on:
  workflow_run:
    workflows: ["first-maven-action"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/firstmavenapp:${{ github.sha }} .

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/firstmavenapp:${{ github.sha }}

    #     uses: helm/kind-action@v1.7.0
    #     - name: Install KIND

    #   - name: Deploy to KIND
    #     run: |
    #       kubectl create deployment myapp --image=${{ secrets.DOCKERHUB_USERNAME }}/myapp:${{ github.sha }} || \
    #       kubectl set image deployment/myapp myapp=${{ secrets.DOCKERHUB_USERNAME }}/myapp:${{ github.sha }}
    #       kubectl expose deployment myapp --type=NodePort --port=8080 || true
    #       kubectl rollout status deployment/myapp
